# Generated by Django 3.2 on 2021-04-10 14:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('canais', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='canal',
            name='inscricoes',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
