# Generated by Django 3.2 on 2021-04-13 18:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('canais', '0002_criacao_inscricao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inscricao',
            options={'ordering': ['canal', 'data']},
        ),
        migrations.AlterUniqueTogether(
            name='inscricao',
            unique_together={('usuario', 'canal')},
        ),
    ]
