version: "3.3"

services:
  database:
    container_name: cursodjangoho_database
    image: postgres
    restart: always
    volumes:
    - ./.pgdata:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=oscar100303
      - POSTGRES_USER=oscarbfs
      - POSTGRES_DB=cursodjangoho
    ports:
      - 5434:5432