# Generated by Django 3.1.7 on 2021-03-24 14:03

from django.db import migrations
from django.utils.text import slugify


def popular_slug(apps, schema_edtor):
    Modulo = apps.get_model('modulos', 'Modulo')
    for modulo in Modulo.objects.all():
        modulo.slug = slugify(modulo.titulo)
        modulo.save()


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0002_auto_20210324_1101'),
    ]

    operations = [
        migrations.RunPython(popular_slug)
    ]
