# Generated by Django 3.1.7 on 2021-04-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0006_video_vimeo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='vimeo_id',
            field=models.CharField(max_length=32),
        ),
    ]
